name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  build:
    needs: quality
    uses: ./.github/workflows/build.yml

  docker:
    needs: build
    uses: ./.github/workflows/docker-build.yml