name: Docker Build

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build \
            -f apps/backend/Dockerfile \
            -t backend:ci \
            .

      - name: Build frontend image
        run: |
          docker build \
            -f apps/frontend/Dockerfile \
            -t frontend:ci \
            .
